services:
  quality-admin-web:
    build: 
      context: ./quality-admin-web
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "1880:1880"
    volumes:
      - ./quality-admin-web:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_API_KEY = "http://localhost:3001"


  quality-admin:
    build:
      context: ./quality-admin
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
      - "4000:4000"
    volumes:
      - ./quality-admin:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_API_KEY = "http://localhost:3002"
      - GMAIL_ADDRESS = "qhrjs407@gmail.com"
      - GMAIL_PASSWORD = "uuxfpjgiwhkfohpo"
      - JWT_KEY = 'qhrjs407!'x  
  quality-chatbot:
    build:
      context: ./quality-chatbot
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./quality-chatbot:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
